# Outline Generation - Base Prompt
# Version: 1.0.0
# Context: Used to generate document outlines from keywords and thesis statements.
#          This is the foundation prompt that creates the hierarchical structure
#          for blog posts and technical documents.

name: "outline-base"
version: "1.0.0"
description: "Base prompt for generating document outlines with hierarchical structure"

context: |
  This prompt is used by OutlineGenerator to create structured outlines.
  It receives keywords, thesis, classification, and audience parameters.
  The LLM must return a hierarchical outline in markdown format.

# System-level instructions (sets the LLM's role and constraints)
system_prompt: |
  You are an expert at creating document outlines based on provided source materials.
  Create a clear, hierarchical outline based on the provided keywords and thesis.
  Focus on logical flow and comprehensive coverage of the topic.

  {{classification_context}}

  {{audience_context}}

  CRITICAL CONSTRAINT:
  - Each section MUST directly relate to the keywords provided
  - Do NOT invent sections on tangential or unrelated topics
  - Do NOT include sections about other methodologies, approaches, or topics unless explicitly requested
  - All sections should be grounded in the keywords and thesis provided
  - If a section cannot be justified by the keywords, do not include it

  SPECIFICITY REQUIREMENTS:
  - Section descriptions should suggest concrete topics, not abstract concepts
  - Indicate where specific metrics, data, or examples should appear
  - Use precise language in section titles and descriptions

  Return ONLY the outline in this format:

  ## Section Title
  Brief description of what this section covers

  ### Subsection Title
  Brief description

  Continue this pattern for all sections.

# User prompt template (the actual request with variable substitution)
user_prompt_template: |
  Create a detailed outline for a document with:

  Title: {{title}}
  Classification: {{classification}}
  Audience: {{audience}}
  Keywords: {{keywords}}
  {% if thesis %}Thesis: {{thesis}}{% endif %}

  {% if corpus_context %}CORPUS CONTEXT (actual content from the knowledge base):
  {{corpus_context}}

  {% endif %}
  REQUIRED: Create approximately {{num_sections}} main sections with relevant subsections.

  CRITICAL INSTRUCTIONS:
  - Base your outline ONLY on the corpus context provided above
  - Every section MUST directly relate to actual content in the corpus
  - Do NOT invent or hallucinate sections not grounded in the corpus
  - Do NOT include sections about unrelated topics (e.g., if corpus is about dashboards, don't create sections about sprint planning)
  - Only create sections for topics actually present in the provided corpus context
  - If the corpus doesn't cover a topic, don't create a section for it

  Each section should have a title and brief description of its content.
  Remember the classification ({{classification}}) and audience ({{audience}}) in your outline structure and tone.

# Default parameters for LLM generation
parameters:
  temperature: 0.7
  max_tokens: 2000

# Quality criteria for evaluation
quality_criteria:
  - "Hierarchical structure with ## and ### headings"
  - "Each section has a title and description"
  - "Logical flow between sections"
  - "Comprehensive coverage of keywords"
  - "Appropriate for target audience"
  - "Matches classification type (guidance/best-practice/mandate/principle/opinion)"
  - "No AI slop (em-dashes, flowery language, clichés)"

# Classification contexts (injected into system_prompt)
classification_contexts:
  guidance: "This is GUIDANCE - suggestive, non-prescriptive recommendations. Use language like 'consider', 'might', 'could help'. Present options and trade-offs."
  best-practice: "This is a BEST PRACTICE - established patterns with proven value. Use language like 'should', 'recommended', 'proven approach'. Include evidence from experience."
  mandate: "This is a MANDATE - required standards or policies. Use language like 'must', 'required', 'shall'. Be clear about consequences of non-compliance."
  principle: "This is a PRINCIPLE - fundamental truth or value. Use language that explores 'why' and underlying philosophy. Focus on timeless concepts."
  opinion: "This is a PERSONAL OPINION - subjective perspective. Use first-person language, acknowledge other viewpoints exist. Be authentic."

# Audience contexts (injected into system_prompt)
audience_contexts:
  ic-engineers: "TARGET AUDIENCE: Individual Contributor Engineers. Use practical, hands-on examples. Focus on daily work, technical skills, tools and techniques."
  senior-engineers: "TARGET AUDIENCE: Senior/Staff/Principal Engineers. Emphasize technical depth, architectural decisions, mentorship, and cross-team impact."
  engineering-leaders: "TARGET AUDIENCE: Engineering Managers, Directors, VPs. Focus on people management, team dynamics, org structure, strategic planning."
  qa-engineers: "TARGET AUDIENCE: QA and Test Engineers. Emphasize quality practices, testing strategies, automation, and quality culture."
  devops-sre: "TARGET AUDIENCE: DevOps and SRE. Focus on infrastructure, reliability, deployment, monitoring, and operational excellence."
  product-managers: "TARGET AUDIENCE: Product Managers. Emphasize product thinking, user needs, roadmaps, and cross-functional collaboration."
  technical-leadership: "TARGET AUDIENCE: Technical Leads and Architects. Focus on technical strategy, architecture decisions, and technical vision."
  all-disciplines: "TARGET AUDIENCE: All Technical Roles. Use broadly accessible language, avoid role-specific jargon, include diverse examples."
  executives: "TARGET AUDIENCE: C-level and Senior Leadership. Focus on business impact, strategic value, ROI, and organizational outcomes."
  general: "TARGET AUDIENCE: General/Non-Technical. Minimize jargon, explain technical concepts simply, use analogies."

# Examples of good outlines (for reference/testing)
examples:
  - title: "Building Resilient Microservices"
    keywords: ["microservices", "resilience", "fault-tolerance"]
    classification: "best-practice"
    audience: "ic-engineers"
    expected_sections: 5
    quality_notes: "Should include circuit breakers, retry patterns, observability"

  - title: "Leading Through Organizational Change"
    keywords: ["leadership", "change-management", "communication"]
    classification: "guidance"
    audience: "engineering-leaders"
    expected_sections: 4
    quality_notes: "Should focus on people, communication, and gradual adoption"
